### ISSUE TITLE
It works locally but after publishing can not define _content/SqliteWasmHelper/browserCache.js

### ISSUE THREAD

**Issue by mahdihaghnegar** [JeremyLikness/SqliteWasmHelper#40]
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: caches is not defined
      ReferenceError: caches is not defined
          at Module.synchronizeDbWithCache (http://myserver.com/_content/SqliteWasmHelper/browserCache.js:5:22)
          at http://myserver.com/_framework/blazor.webassembly.js:1:2878
          at new Promise (<anonymous>)
          at b.beginInvokeJSFromDotNet (http://myserver.com/_framework/blazor.webassembly.js:1:2835)
          at Object.vn [as invokeJSJson] (http://myserver.com/_framework/blazor.webassembly.js:1:58849)
          at http://myserver.com/_framework/dotnet.runtime.8.0.8.80cvijctdx.js:3:178428
          at Ll (http://myserver.com/_framework/dotnet.runtime.8.0.8.80cvijctdx.js:3:179262)
          at http://myserver.com/_framework/dotnet.native.wasm:wasm-function[2650]:0xb5e01
          at http://myserver.com/_framework/dotnet.native.wasm:wasm-function[2547]:0xb22a9
          at http://myserver.com/_framework/dotnet.native.wasm:wasm-function[2540]:0xa5476
Microsoft.JSInterop.JSException: caches is not defined
ReferenceError: caches is not defined
    at Module.synchronizeDbWithCache (http://myserver.com/_content/SqliteWasmHelper/browserCache.js:5:22)
    at http://myserver.com/_framework/blazor.webassembly.js:1:2878
    at new Promise (<anonymous>)
    at b.beginInvokeJSFromDotNet (http://myserver.com/_framework/blazor.webassembly.js:1:2835)
    at Object.vn [as invokeJSJson] (http://myserver.com/_framework/blazor.webassembly.js:1:58849)
    at http://myserver.com/_framework/dotnet.runtime.8.0.8.80cvijctdx.js:3:178428
    at Ll (http://myserver.com/_framework/dotnet.runtime.8.0.8.80cvijctdx.js:3:179262)
    at http://myserver.com/_framework/dotnet.native.wasm:wasm-function[2650]:0xb5e01
    at http://myserver.com/_framework/dotnet.native.wasm:wasm-function[2547]:0xb22a9
    at http://myserver.com/_framework/dotnet.native.wasm:wasm-function[2540]:0xa5476
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at SqliteWasmHelper.BrowserCache.SyncDbWithCacheAsync(String filename)
   at SqliteWasmHelper.SqliteWasmDbContextFactory`1.<RestoreAsync>d__20[[WasmSA.TaskDBContext, WasmSA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at SqliteWasmHelper.SqliteWasmDbContextFactory`1.<CheckForStartupTaskAsync>d__18[[WasmSA.TaskDBContext, WasmSA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at SqliteWasmHelper.SqliteWasmDbContextFactory`1.<CreateDbContextAsync>d__15[[WasmSA.TaskDBContext, WasmSA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at WasmSA.Pages.Home.Load()
   at WasmSA.Pages.Home.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

**Comment by ysmoradi** [comment]
The bit besql version works in production
Demo
https://todo-offline.bitplatform.cc/offline-edit-profile
More info
https://github.com/JeremyLikness/SqliteWasmHelper/issues/34#issue-2059308940
More info 2
https://bitplatform.dev/besql
